load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/8ccdb9d56d07b9169ecd17f1164f251a637c250e.zip"],
  strip_prefix = "googletest-8ccdb9d56d07b9169ecd17f1164f251a637c250e",
)